remote_theme: boycce/github-docs
title: Monastery
description: A simple, straightforward MongoDB ODM
github_url: "https://github.com/boycce/monastery"
port: 4001
basedir: "docs"

# Aux links for the navigation.
aux_links:
  "Monastery on GitHub":
    - "//github.com/boycce/monastery"

defaults:
  -
    scope:
      path: "readme.md"
    values:
      title: "Introduction"
      nav_order: 1
